import json

entries = []

def add(word, pos, irregulars=None, variants=None):
    entries.append({
        "word": word.lower().strip(),
        "pos": pos if isinstance(pos, list) else [pos],
        "irregulars": irregulars or [],
        "variants": variants or []
    })

# Page 41
add("reasonable", ["a"])
add("rebuild", ["v"], ["rebuilt", "rebuilt"])
add("receipt", ["n"])
add("receive", ["v"])
add("receiver", ["n"])
add("recent", ["a"])
add("reception", ["n"])
add("receptionist", ["n"])
add("recipe", ["n"])
add("recite", ["v"])
add("recognise", ["v"], [], ["recognize"])
add("recommend", ["v"])
add("record", ["n", "v"])
add("recorder", ["n"])
add("recover", ["v"])
add("recreation", ["n"])
add("rectangle", ["n", "a"])
add("recycle", ["v"])
add("red", ["n", "a"])
add("reduce", ["v"])
add("refer", ["v"])
add("referee", ["n"])
add("reference", ["n"])
add("reflect", ["v"])
add("reform", ["v", "n"])
add("refresh", ["v"])
add("refrigerator", ["n"])
add("refuse", ["v"])
add("regard", ["v", "n"])
add("regardless", ["a"])
add("register", ["n", "v"])
add("regret", ["n", "v"])
add("regular", ["a"])
add("regulation", ["n"])
add("reject", ["v"])
add("relate", ["v"])
add("relation", ["n"])
add("relationship", ["n"])
add("relative", ["n"])
add("relax", ["v"])
add("relay", ["n", "v"])
add("relevant", ["a"])
add("reliable", ["a"])
add("relief", ["n"])
add("religion", ["n"])
add("religious", ["a"])
add("rely", ["v"])
add("remain", ["v"])
add("remark", ["n"])
add("remember", ["v"])
add("remind", ["v"])
add("remote", ["a"])
add("remove", ["v"])
add("rent", ["n", "v"])
add("repair", ["n", "v"])
add("repeat", ["v"])
add("replace", ["v"])
add("reply", ["n", "v"])
add("report", ["n", "v"])
add("reporter", ["n"])
add("represent", ["v"])
add("representative", ["n"])

# Page 42
add("republic", ["n"])
add("reputation", ["n"])
add("request", ["n"])
add("require", ["v"])
add("requirement", ["n"])
add("rescue", ["v"])
add("research", ["n"])
add("resemble", ["v"])
add("reservation", ["n"])
add("reserve", ["n", "v"])
add("resign", ["v"])
add("resist", ["v"])
add("respect", ["v", "n"])
add("respond", ["v"])
add("responsibility", ["n"])
add("rest", ["n", "v"])
add("restaurant", ["n"])
add("restriction", ["n"])
add("result", ["n"])
add("retell", ["v"])
add("retire", ["v"])
add("return", ["v"])
add("review", ["v", "n"])
add("revision", ["n"])
add("revolution", ["n"])
add("reward", ["n"])
add("rewind", ["v"])
add("rhyme", ["n", "v"])
add("rice", ["n"])
add("rich", ["a"])
add("rid", ["v"], ["rid", "rid", "ridded", "ridded"])
add("riddle", ["n"])
add("ridiculous", ["a"])
add("ride", ["v", "n"], ["rode", "ridden"])
add("right", ["n", "a", "ad"])
add("rigid", ["a"])
add("ring", ["v", "n"], ["rang", "rung"])
add("ripe", ["a"])
add("ripen", ["v"])
add("rise", ["v"], ["rose", "risen"])
add("risk", ["n", "v"])
add("river", ["n"])
add("road", ["n"])
add("roast", ["v"])
add("rob", ["v"])
add("robot", ["n"])
add("rock", ["n"])
add("rocket", ["n"])
add("role", ["n"])
add("roll", ["v", "n"])
add("roof", ["n"])
add("room", ["n"])
add("rooster", ["n"])
add("root", ["n"])
add("rope", ["n"])
add("rose", ["n"])
add("rot", ["v"])
add("rough", ["a"])
add("round", ["ad", "prep", "a"])
add("roundabout", ["a", "n"])
add("routine", ["n"])

# Page 43
add("row", ["n", "v"])
add("royal", ["a"])
add("rubber", ["n"])
add("rubbish", ["n"])
add("rude", ["a"])
add("rugby", ["n"])
add("ruin", ["v", "n"])
add("rule", ["n", "v"])
add("ruler", ["n"])
add("run", ["v"], ["ran", "run"])
add("rush", ["v"])
add("sacred", ["a"])
add("sacrifice", ["v"])
add("sad", ["a"])
add("sadness", ["n"])
add("safe", ["a"])
add("safety", ["n"])
add("sail", ["n", "v"])
add("sailor", ["n"])
add("salad", ["n"])
add("salary", ["n"])
add("sale", ["n"])
add("salesgirl", ["n"])
add("salesman", ["n"], ["salesmen", "saleswomen"], ["saleswoman"])
add("salt", ["n"])
add("salty", ["a"])
add("salute", ["n", "v"])
add("same", ["n", "a"])
add("sand", ["n"])
add("sandwich", ["n"])
add("satellite", ["n"])
add("satisfaction", ["n"])
add("satisfy", ["v"])
add("saucer", ["n"])
add("sausage", ["n"])
add("save", ["v"])
add("say", ["v"], ["said", "said"])
add("saying", ["n"])
add("scan", ["v"])
add("scar", ["n"])
add("scare", ["v"])
add("scarf", ["n"])
add("scene", ["n"])
add("scenery", ["n"])
add("sceptical", ["a"], [], ["skeptical"])
add("schedule", ["n", "v"])
add("scholar", ["n"])
add("scholarship", ["n"])
add("school", ["n"])
add("schoolbag", ["n"])
add("schoolboy", ["n"], [], ["schoolgirl"])
add("schoolmate", ["n"])
add("science", ["n"])
add("scientific", ["a"])
add("scientist", ["n"])
add("scissors", ["n"])
add("scold", ["v"])
add("score", ["n", "v"])
add("scratch", ["v", "n"])

# Page 44
add("scream", ["n"])
add("screen", ["n"])
add("sculpture", ["n"])
add("sea", ["n"])
add("seagull", ["n"])
add("seal", ["n"])
add("search", ["n", "v"])
add("seashell", ["n"])
add("seaside", ["n"])
add("season", ["n"])
add("seat", ["n"])
add("seaweed", ["n"])
add("second", ["a", "n"])
add("secret", ["a", "n"])
add("secretary", ["n"])
add("section", ["n"])
add("secure", ["a"])
add("security", ["n"])
add("see", ["v"], ["saw", "seen"])
add("seed", ["n"])
add("seek", ["v"])
add("seem", ["v"])
add("seize", ["v"])
add("seldom", ["ad"])
add("select", ["v"])
add("self", ["n"])
add("selfish", ["a"])
add("sell", ["v"], ["sold", "sold"])
add("semicircle", ["n"])
add("seminar", ["n"])
add("send", ["v"], ["sent", "sent"])
add("senior", ["a", "n"])
add("sense", ["n"])
add("sensitive", ["a"])
add("sentence", ["n"])
add("separate", ["v", "a"])
add("separation", ["n"])
add("serious", ["a"])
add("servant", ["n"])
add("serve", ["v"])
add("service", ["n"])
add("session", ["n"])
add("set", ["v", "n"], ["set", "set"])
add("settle", ["v"])
add("settlement", ["n"])
add("settler", ["n"])
add("several", ["pron", "a"])
add("severe", ["a"])
add("sew", ["v"], ["sewed", "sewn", "sewed"])
add("sex", ["n"])
add("shabby", ["a"])
add("shade", ["n"])
add("shadow", ["n"])
add("shake", ["v"], ["shook", "shaken"])
add("shall", ["v"])
add("shallow", ["a"])
add("shame", ["n"])
add("shape", ["n", "v"])
add("share", ["v"])
add("shark", ["n"])
add("sharp", ["a"])
add("sharpen", ["v"])

# Page 45
add("sharpener", ["n"])
add("shave", ["v"], ["shaved", "shaved", "shaven"])
add("shaver", ["n"])
add("she", ["pron"])
add("sheep", ["n"], ["sheep"])
add("sheet", ["n"])
add("shelf", ["n"], ["shelves"])
add("shelter", ["n"])
add("shine", ["v"], ["shone", "shone"])
add("ship", ["n", "v"])
add("shirt", ["n"])
add("shock", ["v"])
add("shoe", ["n"])
add("shoot", ["v", "n"], ["shot", "shot"])
add("shop", ["v", "n"])
add("shopkeeper", ["n"])
add("shopping", ["n"])
add("shore", ["n"])
add("short", ["a"])
add("shortcoming", ["n"])
add("shortly", ["ad"])
add("shorts", ["n"])
add("shot", ["n"])
add("should", ["v"])
add("shoulder", ["n"])
add("shout", ["n", "v"])
add("show", ["v", "n"], ["showed", "shown", "showed"])
add("shower", ["n"])
add("shrink", ["v"], ["shrank", "shrunk", "shrunk", "shrunken"])
add("shut", ["v"], ["shut", "shut"])
add("shuttle", ["n"])
add("shy", ["a"])
add("sick", ["a"])
add("sickness", ["n"])
add("side", ["n"])
add("sideroad", ["n"], [], ["sidewalk"])
add("sideways", ["ad"])
add("sigh", ["v", "n"])
add("sight", ["n"])
add("sightseeing", ["n"])
add("signal", ["n"])
add("signature", ["n"])
add("significance", ["n"])
add("silence", ["n"])
add("silent", ["a"])
add("silk", ["n"])
add("silly", ["a"])
add("silver", ["n"])
add("similar", ["a"])
add("simple", ["a"])
add("simplify", ["v"])
add("since", ["ad", "conj", "prep"])
add("sincerely", ["ad"])
add("sing", ["v"], ["sang", "sung"])
add("single", ["a"])
add("sink", ["v", "n"], ["sank", "sunk"])
add("sir", ["n"])
add("sister", ["n"])
add("sit", ["v"], ["sat", "sat"])

# Page 46
add("situation", ["n"])
add("size", ["n"])
add("skate", ["v"])
add("skateboard", ["n"])
add("ski", ["n", "v"])
add("skilful", ["a"])
add("skill", ["n"])
add("skin", ["n"])
add("skip", ["v"])
add("skirt", ["n"])
add("sky", ["n"])
add("skyscraper", ["n"])
add("slave", ["n"])
add("slavery", ["n"])
add("sleep", ["n"])
add("sleep", ["v"], ["slept", "slept"])
add("sleepy", ["a"])
add("sleeve", ["n"])
add("slice", ["n"])
add("slide", ["n", "v"])
add("slight", ["a"])
add("slim", ["a"])
add("slip", ["n"])
add("slow", ["ad"])
add("small", ["a"])
add("smart", ["a"])
add("smell", ["v", "n"], ["smelt", "smelt"], ["smelled", "smelled"])
add("smile", ["n", "v"])
add("smog", ["n"])
add("smoke", ["n", "v"])
add("smoker", ["n"])
add("smooth", ["a"])
add("snake", ["n"])
add("sneaker", ["n"])
add("sneeze", ["v"])
add("sniff", ["v"])
add("snow", ["n", "v"])
add("snowy", ["a"])
add("so", ["ad", "conj"])
add("soap", ["n"])
add("sob", ["n", "v"])
add("soccer", ["n"])
add("social", ["a"])
add("socialism", ["n"])
add("socialist", ["a"])
add("society", ["n"])
add("sock", ["n"])
add("socket", ["n"])
add("sofa", ["n"])
add("soft", ["a"])
add("software", ["n"])
add("soil", ["n"])
add("solar", ["a"])
add("soldier", ["n"])
add("solid", ["a", "n"])
add("some", ["a", "pron"])
add("somebody", ["pron"])
add("somehow", ["ad"])
add("someone", ["pron"])
add("something", ["pron"])
add("sometimes", ["ad"])

# Page 47
add("somewhere", ["ad"])
add("son", ["n"])
add("song", ["n"])
add("soon", ["ad"])
add("sorrow", ["n"])
add("sorry", ["a"])
add("sort", ["v", "n"])
add("soul", ["n"])
add("sound", ["v", "n"])
add("soup", ["n"])
add("sour", ["a"])
add("south", ["a", "ad", "n"])
add("southeast", ["n"])
add("southern", ["a"])
add("southwest", ["n"])
add("souvenir", ["n"])
add("sow", ["v"], ["sowed", "sown", "sowed"])
add("space", ["n"])
add("spaceship", ["n"])
add("spade", ["n"])
add("spare", ["a"])
add("sparrow", ["n"])
add("speak", ["v"], ["spoke", "spoken"])
add("speaker", ["n"])
add("spear", ["n"])
add("special", ["a"])
add("specialist", ["n"])
add("specific", ["a"])
add("speech", ["n"])
add("speed", ["n", "v"])
add("spell", ["v"])
add("spelling", ["n"])
add("spend", ["v"], ["spent", "spent"])
add("spin", ["v", "n"])
add("spirit", ["n"])
add("spiritual", ["a"])
add("spit", ["v"])
add("splendid", ["a"])
add("split", ["v"])
add("spoken", ["a"])
add("spokesman", ["n"], ["spokesmen", "spokeswomen"], ["spokeswoman"])
add("sponsor", ["n"])
add("spoon", ["n"])
add("spoonful", ["n"])
add("sport", ["n"])
add("spot", ["n", "v"])
add("spray", ["n", "v"])
add("spread", ["v"], ["spread", "spread"])
add("spring", ["n"])
add("spy", ["n", "v"])
add("square", ["n", "a"])
add("squeeze", ["v"])
add("squirrel", ["n"])
add("stable", ["a"])
add("stadium", ["n"])
add("staff", ["n"])
add("stage", ["n"])
add("stain", ["n"])
add("stainless", ["a"])
add("stair", ["n"])
add("stamp", ["n"])

# Page 48
add("stand", ["v", "n"], ["stood", "stood"])
add("standard", ["n", "a"])
add("star", ["n"])
add("stare", ["v"])
add("start", ["v"])
add("starvation", ["n"])
add("starve", ["v"])
add("state", ["n"])
add("station", ["n"])
add("statement", ["n"])
add("statesman", ["n"], ["statesmen", "stateswomen"], ["stateswoman"])
add("statistics", ["n"])
add("statue", ["n"])
add("status", ["n"])
add("stay", ["n", "v"])
add("steady", ["a"])
add("steak", ["n"])
add("steal", ["v"], ["stole", "stolen"])
add("steam", ["n"])
add("steel", ["n"])
add("steep", ["a"])
add("step", ["n", "v"])
add("steward", ["n"])
add("stewardess", ["n"])
add("stick", ["v", "n"], ["stuck", "stuck"])
add("still", ["a", "ad"])
add("stocking", ["n"])
add("stomach", ["n"])
add("stone", ["n"])
add("stop", ["n", "v"])
add("storage", ["n"])
add("store", ["n", "v"])
add("storm", ["n"])
add("story", ["n"])
add("stout", ["a"])
add("stove", ["n"])
add("straight", ["a", "ad"])
add("straightforward", ["a", "ad"])
add("strait", ["n"])
add("strange", ["a"])
add("stranger", ["n"])
add("straw", ["n"])
add("strawberry", ["n"])
add("stream", ["n"])
add("street", ["n"])
add("strength", ["n"])
add("strengthen", ["v"])
add("stress", ["n", "v"])
add("strict", ["a"])
add("strike", ["v", "n"], ["struck", "struck", "stricken"])
add("string", ["n"])
add("strong", ["a"])
add("struggle", ["v"])
add("stubborn", ["a"])
add("student", ["n"])
add("studio", ["n"])
add("study", ["v", "n"])
add("stupid", ["a"])
add("style", ["n"])
add("subject", ["n"])

# Page 49
add("subjective", ["a"])
add("submit", ["v"])
add("subscribe", ["v"])
add("substitute", ["v"])
add("succeed", ["v"])
add("success", ["n"])
add("successful", ["a"])
add("such", ["ad", "pron", "a"])
add("suck", ["v"])
add("sudden", ["a"])
add("suffer", ["v"])
add("suffering", ["n"])
add("sugar", ["n"])
add("suggest", ["v"])
add("suggestion", ["n"])
add("suit", ["v", "n"])
add("suitable", ["a"])
add("suitcase", ["n"])
add("suite", ["n"])
add("summary", ["n"])
add("summer", ["n"])
add("sun", ["n"])
add("sunburnt", ["a"])
add("sunlight", ["n"])
add("sunny", ["a"])
add("sunshine", ["n"])
add("super", ["a"])
add("superb", ["a"])
add("superior", ["a", "n"])
add("supermarket", ["n"])
add("supper", ["n"])
add("supply", ["v", "n"])
add("support", ["v", "n"])
add("suppose", ["v"])
add("supreme", ["a"])
add("sure", ["a", "ad"])
add("surface", ["n"])
add("surgeon", ["n"])
add("surplus", ["n"])
add("surprise", ["v", "n"])
add("surround", ["v"])
add("surrounding", ["a"])
add("survive", ["v"])
add("survival", ["n"])
add("suspect", ["v", "n"])
add("suspension", ["n"])
add("swallow", ["v"])
add("swap", ["v"])
add("swear", ["v"], ["swore", "sworn"])
add("sweat", ["n"])
add("sweater", ["n"])
add("sweep", ["v"], ["swept", "swept"])
add("sweet", ["n", "a"])
add("swell", ["v"], ["swelled", "swollen"])
add("swift", ["a"])
add("swim", ["v"], ["swam", "swum"])
add("swing", ["v", "n"])
add("switch", ["v", "n"])
add("sword", ["n"])
add("symbol", ["n"])
add("sympathy", ["n"])
add("symphony", ["n"])

# Page 50
add("symptom", ["n"])
add("system", ["n"])
add("systematic", ["a"])
add("table", ["n"])
add("table tennis", ["n"])
add("tablet", ["n"])
add("tail", ["n"])
add("tailor", ["n"])
add("take", ["v"], ["took", "taken"])
add("tale", ["n"])
add("talent", ["n"])
add("talk", ["n", "v"])
add("tall", ["a"])
add("tank", ["n"])
add("tap", ["n"])
add("tape", ["n"])
add("target", ["n", "v"])
add("task", ["n"])
add("taste", ["n", "v"])
add("tasteless", ["a"])
add("tasty", ["a"])
add("tax", ["n"])
add("taxi", ["n"])
add("taxpayer", ["n"])
add("tea", ["n"])
add("teach", ["v"], ["taught", "taught"])
add("teacher", ["n"])
add("team", ["n"])
add("teamwork", ["n"])
add("teapot", ["n"])
add("tear", ["v", "n"], ["tore", "torn"])
add("tease", ["v"])
add("technical", ["a"])
add("technique", ["n"])
add("technology", ["n"])
add("teenager", ["n"])
add("telephone", ["n", "v"])
add("telescope", ["n"])
add("television", ["n"])
add("tell", ["v"], ["told", "told"])
add("temperature", ["n"])
add("temple", ["n"])
add("temporary", ["a"])
add("tend", ["v"])
add("tendency", ["n"])
add("tennis", ["n"])
add("tense", ["a"])
add("tension", ["n"])
add("tent", ["n"])
add("tentative", ["a"])
add("term", ["n"])
add("terminal", ["a", "n"])
add("terrible", ["a"])
add("terrify", ["v"])
add("terror", ["n"])
add("test", ["v", "n"])
add("text", ["n"])
add("textbook", ["n"])
add("than", ["conj"])
add("thank", ["v", "n"])

# Page 51
add("thankful", ["a"])
add("that", ["pron", "conj", "ad"])
add("the", ["art"])
add("theatre", ["n"], [], ["theater"])
add("theft", ["n"])
add("their", ["pron"])
add("theirs", ["pron"])
add("them", ["pron"])
add("theme", ["n"])
add("themselves", ["pron"])
add("then", ["ad"])
add("theoretical", ["a"])
add("theory", ["n"])
add("there", ["int", "n", "ad"])
add("therefore", ["ad"])
add("thermos", ["n"])
add("these", ["a", "pron"])
add("they", ["pron"])
add("thick", ["a"])
add("thief", ["n"], ["thieves"])
add("thin", ["a"])
add("thing", ["n"])
add("think", ["v"], ["thought", "thought"])
add("thinking", ["n"])
add("thirst", ["n"])
add("this", ["a", "pron"])
add("thorough", ["a"])
add("those", ["a", "pron"])
add("though", ["conj"])
add("thought", ["n"])
add("thread", ["n"])
add("thrill", ["n", "v"])
add("thriller", ["n"])
add("throat", ["n"])
add("through", ["prep", "ad"])
add("throughout", ["prep"])
add("throw", ["v"], ["threw", "thrown"])
add("thunder", ["n", "v"])
add("thunderstorm", ["n"])
add("thus", ["ad"])
add("tick", ["v"])
add("ticket", ["n"])
add("tidy", ["a", "v"])
add("tie", ["v", "n"])
add("tiger", ["n"])
add("tight", ["a"])
add("till", ["conj", "prep"])
add("time", ["n", "v"])
add("timetable", ["n"])
add("tin", ["n"])
add("tiny", ["a"])
add("tip", ["n", "v"])
add("tire", ["v"])
add("tired", ["a"])
add("tiresome", ["a"])
add("tissue", ["n"])
add("title", ["n"])
add("to", ["prep"])
add("toast", ["v", "n"])
add("tobacco", ["n"])
add("today", ["ad", "n"])
add("together", ["ad"])

# Page 52
add("toilet", ["n"])
add("tolerate", ["v"])
add("tomato", ["n"])
add("tomb", ["n"])
add("tomorrow", ["ad", "n"])
add("ton", ["n"])
add("tongue", ["n"])
add("tonight", ["ad", "n"])
add("too", ["ad"])
add("tool", ["n"])
add("tooth", ["n"], ["teeth"])
add("toothache", ["n"])
add("toothbrush", ["n"])
add("toothpaste", ["n"])
add("top", ["n"])
add("topic", ["n"])
add("tortoise", ["n"])
add("total", ["a", "n", "v"])
add("touch", ["v"])
add("tough", ["a"])
add("tour", ["n"])
add("tourism", ["n"])
add("tourist", ["n"])
add("tournament", ["n"])
add("toward", ["prep"], [], ["towards"])
add("towel", ["n"])
add("tower", ["n"])
add("town", ["n"])
add("toy", ["n"])
add("track", ["n"])
add("tractor", ["n"])
add("trade", ["n", "v"])
add("tradition", ["n"])
add("traditional", ["a"])
add("traffic", ["n"])
add("train", ["n", "v"])
add("training", ["n"])
add("tram", ["n"])
add("transform", ["v"])
add("translate", ["v"])
add("translation", ["n"])
add("translator", ["n"])
add("transparent", ["a"])
add("transport", ["n", "v"])
add("trap", ["n", "v"])
add("travel", ["n", "v"])
add("traveller", ["n"], [], ["traveler"])
add("treasure", ["n"])
add("treat", ["v"])
add("treatment", ["n"])
add("tree", ["n"])
add("tremble", ["v"])
add("trend", ["n"])
add("trial", ["n"])
add("triangle", ["n"])
add("trick", ["n"])
add("trip", ["n"])
add("trolleybus", ["n"])
add("troop", ["n"])
add("trouble", ["v", "n"])
add("troublesome", ["a"])
add("trousers", ["n"])

# Page 53
add("truck", ["n"])
add("true", ["a"])
add("truly", ["ad"])
add("trunk", ["n"])
add("trust", ["v"])
add("truth", ["n"])
add("try", ["v"])
add("t-shirt", ["n"])
add("tube", ["n"])
add("tune", ["n"])
add("turkey", ["n"])
add("turn", ["v", "n"])
add("turning", ["n"])
add("tutor", ["n"])
add("tv", ["n"], [], ["television"])
add("twice", ["ad"])
add("twin", ["n"])
add("twist", ["v", "n"])
add("type", ["v"])
add("typewriter", ["n"])
add("typical", ["a"])
add("typhoon", ["n"])
add("typist", ["n"])
add("tyre", ["n"], [], ["tire"])
add("ugly", ["a"])
add("umbrella", ["n"])
add("unable", ["a"])
add("unbearable", ["a"])
add("unbelievable", ["a"])
add("uncertain", ["a"])
add("uncle", ["n"])
add("uncomfortable", ["a"])
add("unconditional", ["a"])
add("unconscious", ["a"])
add("under", ["ad", "prep"])
add("underground", ["a", "n"])
add("underline", ["v"])
add("understand", ["v"], ["understood", "understood"])
add("undertake", ["v"], ["undertook", "undertaken"])
add("underwear", ["n"])
add("unemployment", ["n"])
add("unfair", ["a"])
add("unfit", ["a"])
add("unfortunate", ["a"])
add("uniform", ["n"])
add("union", ["n"])
add("unique", ["a"])
add("unit", ["n"])
add("unite", ["v"])
add("universal", ["a"])
add("universe", ["n"])
add("university", ["n"])
add("unless", ["conj"])
add("unlike", ["prep"])
add("unrest", ["n"])
add("until", ["prep", "conj"])
add("unusual", ["a"])
add("unwilling", ["a"])

# Page 54
add("up", ["ad", "a", "n", "prep"])
add("update", ["v", "n"])
add("upon", ["prep"])
add("upper", ["a"])
add("upset", ["a"])
add("upstairs", ["ad"])
add("upward", ["ad"], [], ["upwards"])
add("urban", ["a"])
add("urge", ["v"])
add("urgent", ["a"])
add("us", ["pron"])
add("use", ["n", "v"])
add("used", ["a"])
add("useful", ["a"])
add("useless", ["a"])
add("user", ["n"])
add("usual", ["a"])
add("vacation", ["n"])
add("vacant", ["a"])
add("vague", ["a"])
add("vain", ["n"])
add("valid", ["a"])
add("valley", ["n"])
add("valuable", ["a"])
add("value", ["n"])
add("variety", ["n"])
add("various", ["a"])
add("vase", ["n"])
add("vast", ["a"])
add("vcd", ["n"], [], ["versatile compact disk"])
add("vegetable", ["n"])
add("vehicle", ["n"])
add("version", ["n"])
add("vertical", ["a"])
add("very", ["ad"])
add("vest", ["n"])
add("via", ["prep"])
add("vice", ["n"])
add("victim", ["n"])
add("victory", ["n"])
add("video", ["n"])
add("videophone", ["n"])
add("view", ["n"])
add("village", ["n"])
add("villager", ["n"])
add("vinegar", ["n"])
add("violate", ["v"])
add("violence", ["n"])
add("violent", ["a"])
add("violin", ["n"])
add("violinist", ["n"])
add("virtue", ["n"])
add("virus", ["n"])
add("visa", ["n"])
add("visit", ["n", "v"])
add("visitor", ["n"])
add("visual", ["a"])
add("vital", ["a"])
add("vivid", ["a"])
add("vocabulary", ["n"])

# Page 55
add("voice", ["n"])
add("volcano", ["n"])
add("volleyball", ["n"])
add("voluntary", ["a"])
add("volunteer", ["n", "v"])
add("vote", ["v"])
add("voyage", ["n"])
add("wag", ["v"])
add("wage", ["n"])
add("waist", ["n"])
add("wait", ["v"])
add("waiter", ["n"])
add("waiting-room", ["n"])
add("waitress", ["n"])
add("wake", ["v"], ["woke", "woken"])
add("walk", ["n", "v"])
add("wall", ["n"])
add("wallet", ["n"])
add("walnut", ["n"])
add("wander", ["v"])
add("want", ["v"])
add("war", ["n"])
add("ward", ["n"])
add("warehouse", ["n"])
add("warm", ["a"])
add("warmth", ["n"])
add("warn", ["v"])
add("wash", ["v", "n"])
add("washroom", ["n"])
add("waste", ["n", "v"])
add("watch", ["v", "n"])
add("water", ["n", "v"])
add("watermelon", ["n"])
add("wave", ["n", "v"])
add("wax", ["n"])
add("way", ["n"])
add("we", ["pron"])
add("web", ["n"])
add("website", ["n"])
add("weak", ["a"])
add("weakness", ["n"])
add("wealth", ["n"])
add("wealthy", ["a"])
add("wear", ["v"], ["wore", "worn"])
add("weather", ["n"])
add("wedding", ["n"])
add("weed", ["n"])
add("week", ["n"])
add("weekday", ["n"])
add("weekend", ["n"])
add("weekly", ["a"])
add("weep", ["v"])
add("weigh", ["v"])
add("weight", ["n"])
add("welcome", ["int", "n", "v", "a"])
add("welfare", ["n"])
add("well", ["n"])
add("well", ["ad", "a", "int"], ["better", "best"])
add("west", ["a", "ad", "n"])
add("western", ["a"])

# Page 56
add("westward", ["ad"], [], ["westwards"])
add("wet", ["a"])
add("whale", ["n"])
add("what", ["pron", "a"])
add("whatever", ["conj", "pron"])
add("wheat", ["n"])
add("wheel", ["n"])
add("when", ["conj", "ad"])
add("whenever", ["conj"])
add("where", ["conj", "ad"])
add("wherever", ["conj"])
add("whether", ["conj"])
add("which", ["pron", "a"])
add("whichever", ["pron"])
add("while", ["conj", "n"])
add("whisper", ["v"])
add("whistle", ["n"])
add("white", ["a", "n"])
add("who", ["pron"])
add("whole", ["a"])
add("whom", ["pron"])
add("whose", ["pron"])
add("why", ["ad", "int"])
add("wide", ["a"])
add("widespread", ["a"])
add("widow", ["n"])
add("wife", ["n"])
add("wild", ["a"])
add("wildlife", ["n"])
add("will", ["n"])
add("will", ["v"], ["would"])
add("willing", ["a"])
add("win", ["v"], ["won", "won"])
add("wind", ["n"])
add("wind", ["v"], ["wound", "wound"])
add("window", ["n"])
add("windy", ["a"])
add("wine", ["n"])
add("wing", ["n"])
add("winner", ["n"])
add("winter", ["n"])
add("wipe", ["v"])
add("wire", ["n"])
add("wisdom", ["n"])
add("wise", ["a"])
add("wish", ["n", "v"])
add("with", ["prep"])
add("withdraw", ["v"])
add("within", ["prep"])
add("without", ["prep"])
add("witness", ["v", "n"])
add("wolf", ["n"], ["wolves"])
add("woman", ["n"], ["women"])
add("wonder", ["v", "n"])
add("wonderful", ["a"])
add("wood", ["n"])
add("wool", ["n"])
add("woollen", ["a"], [], ["woolen"])
add("word", ["n"])
add("work", ["n", "v"])
add("worker", ["n"])
add("world", ["n"])

# Page 57
add("worldwide", ["a"])
add("worm", ["n"])
add("worn", ["a"])
add("worried", ["a"])
add("worry", ["n", "v"])
add("worth", ["a"])
add("worthwhile", ["a"])
add("worthy", ["a"])
add("would", ["v"])
add("wound", ["v", "n"])
add("wrestle", ["v"])
add("wrinkle", ["n"])
add("wrist", ["n"])
add("write", ["v"], ["wrote", "written"])
add("wrong", ["a"])
add("x-ray", ["n"])
add("yard", ["n"])
add("yawn", ["v"])
add("year", ["n"])
add("yell", ["v"])
add("yellow", ["a", "n"])
add("yes", ["ad"])
add("yesterday", ["n", "ad"])
add("yet", ["ad"])
add("yoghurt", ["n"])
add("you", ["pron"])
add("young", ["a"])
add("your", ["pron"])
add("yours", ["pron"])
add("yourself", ["pron"], ["yourselves"])
add("youth", ["n"])
add("yummy", ["a"])
add("zebra", ["n"])
add("zero", ["n", "num"])
add("zip", ["v", "n"])
add("zipper", ["n"])
add("zone", ["n"])
add("zoo", ["n"])
add("zoom", ["v"])

# Number tables pages 57-59
num_rows = [
    ("one", "1st", "first"),
    ("two", "2nd", "second"),
    ("three", "3rd", "third"),
    ("four", "4th", "fourth"),
    ("five", "5th", "fifth"),
    ("six", "6th", "sixth"),
    ("seven", "7th", "seventh"),
    ("eight", "8th", "eighth"),
    ("nine", "9th", "ninth"),
    ("ten", "10th", "tenth"),
    ("eleven", "11th", "eleventh"),
    ("twelve", "12th", "twelfth"),
    ("thirteen", "13th", "thirteenth"),
    ("fourteen", "14th", "fourteenth"),
    ("fifteen", "15th", "fifteenth"),
    ("sixteen", "16th", "sixteenth"),
    ("seventeen", "17th", "seventeenth"),
    ("eighteen", "18th", "eighteenth"),
    ("nineteen", "19th", "nineteenth"),
    ("twenty", "20th", "twentieth"),
    ("twenty-one", "21st", "twenty-first"),
    ("twenty-two", "22nd", "twenty-second"),
    ("twenty-three", "23rd", "twenty-third"),
    ("thirty", "30th", "thirtieth"),
    ("forty", "40th", "fortieth"),
    ("fifty", "50th", "fiftieth"),
    ("sixty", "60th", "sixtieth"),
    ("seventy", "70th", "seventieth"),
    ("eighty", "80th", "eightieth"),
    ("ninety", "90th", "ninetieth"),
    ("one hundred", "100th", "one hundredth"),
    ("one hundred one", "101st", "one hundred and first", ["one hundred and one"]),
    ("one hundred two", "102nd", "one hundred and second", ["one hundred and two"]),
    ("three hundred", "300th", "three hundredth"),
    ("one thousand", "1000th", "one thousandth"),
    ("three thousand", "3000th", "three thousandth"),
    ("ten thousand", "10000th", "ten thousandth"),
    ("million", "1000000th", "millionth"),
    ("billion", "1000000000th", "billionth"),
]

for row in num_rows:
    if len(row) == 4:
        card, abbr, ordw, vars_ = row
    else:
        card, abbr, ordw = row
        vars_ = []
    add(card, ["num"], variants=vars_)
    add(abbr, ["num"])
    add(ordw, ["num"])

# Months
months = [
    ("january", "jan."),
    ("february", "feb."),
    ("march", "mar."),
    ("april", "apr."),
    ("may", "may"),
    ("june", "jun."),
    ("july", "jul."),
    ("august", "aug."),
    ("september", "sept."),
    ("october", "oct."),
    ("november", "nov."),
    ("december", "dec."),
]
for m, abbr in months:
    if m != abbr.replace(".", ""):
        add(m, ["n"], variants=[abbr])
    else:
        add(m, ["n"])

# Days
days = [
    ("monday", "mon."),
    ("tuesday", "tues."),
    ("wednesday", "wed."),
    ("thursday", "thurs."),
    ("friday", "fri."),
    ("saturday", "sat."),
    ("sunday", "sun."),
]
for d, abbr in days:
    add(d, ["n"], variants=[abbr])

# Country tables pages 59-61
countries = [
    ("afghanistan", "afghan", "afghan"),
    ("algeria", "algerian", "algerian"),
    ("argentina", "argentinian", "argentinian"),
    ("australia", "australian", "australian"),
    ("austria", "austrian", "austrian"),
    ("belgium", "belgian", "belgian"),
    ("brazil", "brazilian", "brazilian"),
    ("britain", "british", "british", ["u.k.", "the united kingdom"]),
    ("burma", "burmese", "burmese"),
    ("canada", "canadian", "canadian"),
    ("china", "chinese", "chinese"),
    ("colombia", "colombian", "colombian"),
    ("cuba", "cuban", "cuban"),
    ("denmark", "dane", "danish"),
    ("egypt", "egyptian", "egyptian"),
    ("finland", "finn", "finnish"),
    ("france", "french", "french"),
    ("germany", "german", "german"),
    ("greece", "greek", "greek"),
    ("holland", "dutch", "dutch", ["netherlands"]),
    ("hungary", "hungarian", "hungarian"),
    ("india", "indian", "indian"),
    ("indonesia", "indonesian", "indonesian"),
    ("iran", "iranian", "iranian"),
    ("iraq", "iraqi", "iraqi"),
    ("ireland", "irish", "irish"),
    ("israel", "israeli", "israeli"),
    ("italy", "italian", "italian"),
    ("japan", "japanese", "japanese"),
    ("jordan", "jordanian", "jordanian"),
    ("kenya", "kenyan", "kenyan"),
    ("d.p.r.korea", "korean", "korean"),
    ("kuwait", "kuwaiti", "kuwaiti"),
    ("lebanon", "lebanese", "lebanese"),
    ("luxembourg", "luxembourger", "luxembourgish"),
    ("malaysia", "malaysian", "malaysian"),
    ("mexico", "mexican", "mexican"),
    ("new zealand", "new zealander", "zelanian"),
    ("norway", "norwegian", "norwegian"),
    ("pakistan", "pakistani", "pakistani"),
    ("panama", "panamanian", "panamanian"),
    ("philippines", "filipino", "philippine"),
    ("poland", "polish", "polish"),
    ("portugal", "portuguese", "portuguese"),
    ("russia", "russian", "russian"),
    ("singapore", "singaporean", "singaporean"),
    ("south africa", "south african", "south african"),
    ("south korea", "korean", "korean"),
    ("spain", "spanish", "spanish"),
    ("sweden", "swedish", "swedish"),
    ("switzerland", "swiss", "swiss"),
    ("thailand", "thai", "thai"),
    ("turkey", "turk", "turkish"),
    ("u.s.a.", "american", "american"),
    ("vietnam", "vietnamese", "vietnamese"),
]

for row in countries:
    country = row[0]
    person = row[1]
    adj = row[2]
    cvars = row[3] if len(row) > 3 else []
    add(country, ["n"], variants=cvars)
    if person == adj:
        add(person, ["n", "a"])
    else:
        add(person, ["n"])
        add(adj, ["a"])

print(json.dumps(entries, ensure_ascii=False, separators=(',', ':')))
